train_dataset:
  type: baseline
  path: /home/alex/diplom/data/train_dataset/
  batch_size: 3
  num_workers: 6
  pin_memory: True
  shuffle: True
  transforms: True

val_dataset:
  type: baseline
  path: /home/alex/diplom/data/val_dataset/
  batch_size: 1
  num_workers: 1
  shuffle: False
  pin_memory: True
  transforms: True

