name: transformer_inside_baseline_enc_bs_4
n_epoch: 100

base_dir: ./results/
logs_dir: logs
checkpoint_dir: checkpoints

optimizer:
  name: adamw
  lr: 0.0001
  weight_decay: 1e-10

scheduler:
  name: transformer


