name: segformer_b0_classification_all_pos_encod_small_dataset_efficient
n_epoch: 100

base_dir: ./results_copy/classification/
logs_dir: logs
checkpoint_dir: checkpoints

mixed_precision: False

optimizer:
  name: adamw
  lr:
    - 0.00008
    - 0.00008
  weight_decay: 1e-10

scheduler:
  name: transformer


