name: segformer_b0_bs3_pretrained_3_all_pos_encod_xca
n_epoch: 46

base_dir: ./results_copy/
logs_dir: logs
checkpoint_dir: checkpoints

mixed_precision: False

optimizer:
  name: adamw
  lr:
    - 0.00004
    - 0.00008
  weight_decay: 1e-10

scheduler:
  name: transformer

#load_optim: True
#continue_name: segformer_b0_bs3_pretrained_first_pos_encod
#start_epoch: 37

